import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read','clipboard-write'] });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5173';
await mkdir('/tmp/transitreach-v05', { recursive: true });
await page.goto(`${base}/map?lat=22.543&lon=114.058&name=福田CBD&budget=15&mode=reverse&departure=weekend-day`, {waitUntil:'domcontentloaded',timeout:120000});
await page.getByText('15 分钟通勤圈 · 居住选区参考', {exact:true}).waitFor({timeout:60000});
assert.equal(await page.getByPlaceholder('输入工作地点或目的地').count(), 1);
assert.ok(page.url().includes('departure=weekend-day'));
await page.getByRole('button', {name:'复制分享链接'}).click();
assert.equal(await page.evaluate(() => navigator.clipboard.readText()), page.url());
await page.getByRole('checkbox').check();
await page.locator('.budget-layer-15').first().waitFor({state:'attached',timeout:60000});
for (const budget of [15,30,45,60]) assert.ok(await page.locator(`.budget-layer-${budget}`).count() > 0);
await page.screenshot({path:'/tmp/transitreach-v05/desktop.png'});
const downloadEvent = page.waitForEvent('download', {timeout:60000});
await page.getByRole('button',{name:'保存截图',exact:true}).click();
const download = await downloadEvent;
await download.saveAs('/tmp/transitreach-v05/export.png');
await page.getByRole('button',{name:'清除',exact:true}).click();
await page.getByRole('heading',{name:'📍 选择工作地点'}).waitFor();
assert.equal(new URL(page.url()).searchParams.has('lat'),false);
assert.equal(await page.locator('.reach-area').count(),0);
await page.getByRole('button',{name:'深圳北',exact:true}).click();
await page.locator('.budget-layer-15').first().waitFor({state:'attached',timeout:60000});
assert.ok(page.url().includes('stop='));
await page.setViewportSize({width:375,height:812});
await page.screenshot({path:'/tmp/transitreach-v05/mobile-collapsed.png'});
assert.equal(await page.locator('.config-details').isVisible(),false);
await page.getByRole('button',{name:'━ 展开配置',exact:true}).click();
assert.equal(await page.locator('.config-details').isVisible(),true);
await page.screenshot({path:'/tmp/transitreach-v05/mobile-expanded.png'});
assert.deepEqual(errors,[]);
console.log(JSON.stringify({ok:true,export:download.suggestedFilename(),url:page.url(),errors}));
await browser.close();
